name: CI
on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: dotnet build
    - uses: actions/upload-artifact@v2
      with:
        path: MisakaTranslator-WPF/bin/Debug
